### ISSUE TITLE
Build completes and does not end properly

### ISSUE THREAD

**Issue by hooray** [evont/vite-plugin-spritesmith#1]
我使用项目里 example 目录测试，当版本号是 0.0.2 时正常，当我手动将插件升级到 0.1.0 后，则出现问题，构建完成后，无法正常结束，需要手动按 ctrl + c 强制结束。

Translation:
I use the example directory in the project to test, when the version number is 0.0.2, it works fine, when I manually upgrade the plugin to 0.1.0, there is a problem, after the build is completed, it does not end normally, you need to manually press ctrl + c to force the end.

![image](https://user-images.githubusercontent.com/1574903/131301950-4a1fade6-3b93-4651-b158-3746419e3d07.png)

**Comment by evont** [comment]
Option watch is `true` by default, it should be disabled in production mode. Will fix it in the future.
```javascript
Spritesmith({
      watch: process.env.NODE_ENV !== 'production',
    //...
})
```

**Comment by hooray** [comment]
thx, it works normally right now
